import { EntityMetadataMap } from '@osveh/data-kit';

export const entityMetadata: EntityMetadataMap = {
  DisabilityType: {},
  BlackListOwner: {},
  BlackListType: {},
  ReligionType: {},
  ReligionTypeDetail: { selectId: (item) => item.religionDetailId },
  RelationShipType: { selectId: (item) => item.relationshipTypeId },
  RelationShipDetail: { selectId: (item) => item.relationshipDetailId },
  VeteranType: {},
  EmploymentType: {},
  EducationMajor: { selectId: (item) => item.educationMajorID },
  EducationMajorGroup: {},
  ParamJobs: {},
  ParamJobGroups: {},
  OccupationSections: {},
  OccupationGroup: {},
  OccupationDepartmans: { selectId: (item) => item.departmanID },
  ParamCountry: {},
  ParamCities: {},
  CodeParam: { selectId: (item) => `${item.groupId}-${item.id} ` },
  RCustomerInquiry: {},
  DeadCustomerType: { selectId: (i)=> i.customerId},
  WorkPlaceTypes: {},
  ParamProvinces: {},
  EducationAcademies: { selectId: (item) => item.educationAcademyID },
  EducationDegrees: {},
  RegisterRealCustomer: {},
  ApproveRcustomer: {},
  ContactTypes: {},
  FetchCustomer: {},
  RelationshipsRules: {},
  UnitsInfo: {},
    Customer:{},
    IndividualBatch:{},
    IndividualBatchFileDetail:{},
  IndividualCustomer: {},
  AdvanceIndividualCustomer: {},
};
