export interface RCustomerInquiry {
  "nationalCode":string;
  "firstName":string;
  "lastName":string;
  "fatherName":string;
  "birthDate":number;
  "isAlive":number;
  "gender":number;
  "identityNumber":number;
  "identityAlphabeticPart":string;
  "identityNumericPart":number;
  "identitySerial":number;
  "identityIssueCityId":number;
  "birthCityId":number;
  "postalCode":number;
  "inquiryId":number;
  "inquiryDate":number;
  "shahabCode":number;
}
